title: Rajas Joshi # your name (or website title) here
logo: "/images/circle-cropped.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <Font size='2'>I am an Electronics Enigneering graduate.
  My interest of work is in Robotics and Embedded Systems.
  <br><br>
  <font size='2'>The tools and softwares, I have worked with are as follows:
  
  1. Hardware: ARM, AVR, ESP32, Raspberry Pi, 8051.
  
  2. Software: ROS1, ROS2, C++, Python, OpenCV, PCL, Matlab,
               MBED OS, Azure IOT, FREERTOS.</font>
  <br><br>
  <a href="https://www.linkedin.com/in/rajasjoshi99/">View My LinkedIn Profile</a> 
  
  
theme: jekyll-theme-minimal

